language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: DEPENDENCIES=beta

before_script:
  - composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

install: composer install --dev

script: phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
